feat: edit.vueの実装
traPtitech/anke-to-v3-UI pull request #35
Opened 2024-01-18 10:11 UTC by Qro-384

やったこと
・responses/[responseID]/edit.vueの作成
・edit.vueとnew.vueのコンポーネントの共通化
・コンポーネントの名前をnew-*からbased-*に変更

2024-01-22 08:36 UTC, cp-20 requested changes
ちょっとしたことが2つと、設計に関してのことが1つ、対応お願いします🙏

2024-01-22 08:36 UTC, cp-20 commented on nuxt.config.ts
>    },
この変更は入れないで欲しいかな

2024-01-22 08:36 UTC, cp-20 commented on components/based-response-form/based-response-form.vue
>        </Button>
この部分を切り替えるんじゃなくて、このactionsの部分を外部から入れられるような設計にしてほしい (Slot使うか外部からやるか)

参考: https://ja.vuejs.org/guide/components/slots

2024-01-22 08:36 UTC, cp-20 commented on components/based-response-form/based-response-form.vue
全体としてだけど、`based-response-form`より`form-response-base`の方が自然かも？

2024-01-25 09:58 UTC, Qro-384 commented
修正しました、確認お願いします

2024-02-16 07:36 UTC, cp-20 requested changes
- `form-response-base` -> `response-form-base`
- 編集が押された時にとりあえずconsole.logとかして欲しい

2024-11-21 09:08 UTC, Qro-384 commented
多分できてそう

2024-11-22 09:21 UTC, cp-20 requested changes

2024-11-22 09:21 UTC, cp-20 commented on components/response-form-base/question-element/question-scale-input.vue
> +~/components/response-form-base/form-response-base-settings~/components/response-form-base/questionnaire-settings
これ消して欲しいです！ (他のところも同じ)

2024-11-22 09:23 UTC, cp-20 commented
あと↓の一時保存消して欲しいです！
![image](https://github.com/user-attachments/assets/200526f7-9f88-4d71-84dd-c38468397f4c)

2024-12-09 15:25 UTC, cp-20 requested changes
コメントした箇所を直してもらえると嬉しいです！

2024-12-09 15:25 UTC, cp-20 commented on components/response-form-base/response-form-base.vue
> +      </SendButton>
handleSend のロジックは使う場所によって変わるはずなので、外部から変更できるようにしてください！(MUST)

あと MUST ではないですが、将来の拡張性を考えると save と send 以外もできるようにしておく方が良いかもしれません。具体的にはこのボタンの並び全体を `template` にすると良いと思います。

2024-12-09 15:25 UTC, cp-20 commented on components/response-form-base/send-button.vue
> +</style>
MUST ではないですが、`send-button.vue` と `save-button.vue` の内容は本質的にほとんど同じなのでまとめられると良いかもしれません (本質はアイコンを付けたいだけだと思うので)

2024-12-12 09:44 UTC, Qro-384 commented
handleSendのロジックの変更と、ボタンに参照されるコンポーネントの(button-element.vueへの)統一をしました、レビューお願いします

2024-12-14 14:23 UTC, cp-20 approved these changes
今のままでも動きそう:+1:

ただ `sendApi` ってprops生やすより emit されてる `@save` とか `@send` とか使った方がスッキリするかなって思いました

(いくつかコメントしたけどもうマージしちゃっても大丈夫です)

2024-12-14 14:23 UTC, cp-20 commented on components/response-form-base/response-form-base.vue
> +        @click-button="handleSave"
`@click` だけでいいかも (直さなくても良い)

2024-12-14 14:23 UTC, cp-20 commented on components/response-form-base/response-form-base.vue
> +
このクラスは存在しなくなってそう？

2024-12-17 06:18 UTC, merged